var fname = 'I am';
var lname = 'Dipu Biswas';
console.log(fname, lname);
console.log(lname.substr(4, 7));
console.log(fname.toLowerCase());
console.log(lname.toUpperCase());
var str1 = 'This is more than      ';
console.log(str1.trim());
console.log(fname.concat(' ', lname));
console.log(str1.split(' '));